### ISSUE TITLE
add CRD, serviceaccount, dashboard role and rolebinding

### ISSUE THREAD

**Issue by ram4ibm** [OpenUnison/openunison-k8s-login-activedirectory#19]
https://github.com/OpenUnison/openunison-k8s-login-activedirectory/blob/e77fad22e6f34aa6a656bd3f98f82d86a843cc73/src/main/bash/delete_everything.sh#L6

It would be complete if you have deploymentconfig with the pod to delete the CRD, serviceaccount, role and rolebindings which was created by deploy.js. preferably, all the artefacts created by deploy.js

**Comment by mlbiam** [comment]
This has been updated
