### ISSUE TITLE
auth defaultForm - null action

### ISSUE THREAD

**Issue by jerer** [OpenUnison/openunison-k8s-login-activedirectory#23]
I try to configure authentication on bare metal Kubernetes using this guide.

I completed all steps in instruction, pods in openunison namespace are running, pod logs contain no errors. I can access login url (https://OU_HOST/auth/forms/defaultForm.jsp), but form action is null, so when i try to login i'm redirected to https://OU_HOST/auth/forms/null.

I searched openunison code, it seems the problem is with [this](https://github.com/TremoloSecurity/OpenUnison/blob/master/unison/open-unison-webapp/src/main/webapp/auth/forms/default-form.jsp) file, TREMOLO_AUTH_URI is not set, but I couldn't find why.

**Comment by mlbiam** [comment]
@jerer the issue is a cookie problem.  Does your `OU_HOST` and `OU_COOKIE_DOMAIN` line up?  For example if `OU_HOST` is k8sou.tremolo.lan then `OU_COOKIE_DOMAIN` must be tremolo.lan.

**Comment by jerer** [comment]
Cookie setting was removed in [https://github.com/OpenUnison/openunison-k8s-login-activedirectory/commit/9e265670767bfd1bd8dd60a9d264643e9d2c96be#diff-04c6e90faac2675aa89e2176d2eec7d8](url), so i closed issue
