### ISSUE TITLE
NullPointerException during artifact deployment

### ISSUE THREAD

**Issue by davideagen** [OpenUnison/openunison-k8s-login-activedirectory#30]
Started with a 1.14.1 Kubernetes cluster using kube-router for networking. Installed ingress-nginx mandatory and nodeport from https://kubernetes.github.io/ingress-nginx/deploy. Created the namespace, secret, and configmap and then depoyed the portal.

Both artifact deployment pods exit Terminated:Error. Logs show:

> ...
> Create OpenUnison Secret
> Exception in thread "main" java.lang.NullPointerException
> 	at sun.security.pkcs12.PKCS12KeyStore.createEncryptedData(PKCS12KeyStore.java:1687)
> 	at sun.security.pkcs12.PKCS12KeyStore.engineStore(PKCS12KeyStore.java:1213)
> 	at java.security.KeyStore.store(KeyStore.java:1377)
> 	at com.tremolosecurity.kubernetes.artifacts.util.CertUtils.encodeKeyStore(CertUtils.java:251)
> 	at jdk.nashorn.internal.scripts.Script$\^eval\_.:program(<eval>:319)
> 	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)
> 	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
> 	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
> 	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:449)
> 	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:406)
> 	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:402)
> 	at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:150)
> 	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:249)
> 	at com.tremolosecurity.kubernetes.artifacts.run.RunDeployment.main(RunDeployment.java:106)

**Comment by mlbiam** [comment]
> Created the namespace, secret, and configmap and then depoyed the portal.

Which namespace/secret/configmap?  You created a secret manually?  What deployer of k8s (ie kubeadm, canonical, etc)

**Comment by davideagen** [comment]
The cluster was created with kubeadm.

The process followed was:

# Download https://raw.githubusercontent.com/OpenUnison/openunison-k8s-login-activedirectory/master/src/main/yaml/artifact-deployment.yaml
# Create auth-deploy/configmap directory and put LDAP server root CA in it with a .pem extension
# Create auth-deploy/secrets directory and put modified copy of input.props in it.
# kubectl create namespace openunison-deploy
# kubectl create configmap extracerts --from-file auth-deploy/configmaps -n openunison-deploy
# kubectl create secret generic input --from-file auth-deploy/secrets -n openunison-deploy
# kubectl create -f portal-deployment.yaml

**Comment by mlbiam** [comment]
did you rename `artifact-deployment.yaml` --> `portal.yaml`?

**Comment by davideagen** [comment]
Yes I did, sorry I forgot to mention that. Nothing was changed in the file, it was just renamed.

**Comment by mlbiam** [comment]
Can you try remote shelling into any container in the cluster and check `/var/run/secrets/kubernetes.io/serviceaccount/ca.crt` to see if there are multiple certs?  For instance in one of my clusters I ran:

```
$ kubectl exec -ti nginx-ingress-controller-76c86d76c4-4mlv6 bash -n ingress-nginx
www-data@nginx-ingress-controller-76c86d76c4-4mlv6:/etc/nginx$ cat /var/run/secrets/kubernetes.io/serviceaccount/ca.crt 
-----BEGIN CERTIFICATE-----
MIIEyDCCArCgAwIBAgIRAPCgINH10X9Mu2tzGTjHHc8wDQYJKoZIhvcNAQELBQAw
DTELMAkGA1UEAxMCY2EwHhcNMTkwNDE1MTc0OTMwWhcNMjEwNDE0MTc0OTMwWjAN
MQswCQYDVQQDEwJjYTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAKFq
AhAg1VMv1+rckoNX5RUJKzEMT+5ESnqzw8k426b88X5j8wuVFOgqu+A7C0Kx9/6s
YJviLbtNBO5VcACpPU0aCSdZhwFRV+3D067YqkkIXt8pvhkHAk0bvxAazzKwhIQM
IFvr2ysj4LtFrEBeLZIF0eyg0UP0vY3BxzPMF9TcbkiWZbJQ3XMRFL5LA2q8WveP
ceNPMy34Ws1YrokNY+IgFeVi8HxQJ2x/Im30qc372oF+NaXFkFt7PSt1lMSucfVN
hVraAoQvvKtpo2fTYyZ4cIZd8143XfnJKcMCngnL6uq2nWMXlaur1DSTEHDds3rD
WAQdeMbJugPMg8Mflj3SZKDx/wvIHbqiJ0ShAvHqPzq7kqK+AoFc83CBoIeqY1jH
e/nT5A9P4Mxp/FQ50t2O28+aY2Vy4rKK72SrLRML7QA0ITpySxNxuruthvYyzklR
F5BLXyyoQDfehuozk0vAhOramSIkZPRhIoXgGyWu5XcZWMgNZd2u37ArpQbMbEIW
cHSzAyzcKP3gSP4y5U62eJp0At2rCTm83C1HetnVxMmM+Ak2/vNlvW71D3nhx44+
cM7RaojDxp6j2KTEU55IVaLltr1SWiGyIXvjZACp1cxZxTnCQv/2AKvO8R4quOo+
RI/JRIK4ZwVkSPTHmXuYp6ep361anxtZnUxbSNQ5AgMBAAGjIzAhMA4GA1UdDwEB
/wQEAwICpDAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBCwUAA4ICAQBwFtX8
dFeFpl8i8zNJOTc2j/dFasArc6qHJDAvlGciLFUWnlv0FZRux4HFJRh2ivKwmL9q
iY1gz4x6s5g7mjYH+edPb+zpWF7PSd/Hqqbb1y1ovQh2hg4BGCvZNnjRl8dywEVL
oUhoUDt6o5/begK/DLa1nywQ7ENsYdSvWgiJ4bPQ/UUpX3r1ooMK1FxsmYGkHLN4
5OA7c/teWUz4AWeECyagAA7Io85B4xD2R+zklIz+z5IbsYDnpkvUEWfgFuqPaJpN
1zUB9DTL9p/5KjtnnlkwaYnB4C5lj4btZPofCV8RcKzm9O66tvc+tz5o/EhpnQPd
06uZ6K5rgXWT2ZfYl1vvTrrLzTDUv5YHRCDRRFMjXdiFnlghSk16FQRwHhy6FxsS
SntZVR8cmsmIxg84KRAGJX/ga802RWWmJnutb6SEcFts9o16xXfFQyLH+D/RAolB
E9E6cpLTvLx1OlnYROW5NyIKioDG813Ech4g+Jc67EYhimNEJO1/ncb9NGVGULfp
H1BTJfHdt/Sfj3DpidmTZPc4WpaniJJ6Td9pkqa5JWZcqYZW2CrcgSnZW3FW42q6
PID7tRQoup6HabH15pEPztAvzmKvpCnaR4Mn8/frnfpkoXac73ZNDSg6ak240YFm
L010PKiv+n1EAKf9oPqgXLB49boksZFw1QtzYQ==
-----END CERTIFICATE-----
```

**Comment by mlbiam** [comment]
> Create auth-deploy/configmap directory and put LDAP server root CA in it with a .pem extension

Did you name it `trusted-adldaps.pem` (exactly)?  The script is looking for that filename specifically.

**Comment by davideagen** [comment]
Thank you, that was the problem. I missed the part where the CA cert had to be named `trusted-adldaps.pem`. Once I renamed it to that the deployment finished succesfully.

**Comment by mlbiam** [comment]
Excellent!
