### ISSUE TITLE
kubectl config needs updating on every login

### ISSUE THREAD

**Issue by davideagen** [OpenUnison/openunison-k8s-login-activedirectory#32]
Login portal is working to authenticate users and populate group information. Proxy access to the dashboard works correctly and kubectl commands succeed once kubectl is configured per the web UI instructions.

When a session times out and the user authenticates again, the kubectl configuration must be replaced in order for commands to succeed. If the previous kubectl config is used, commands fail with a 401 status code.

Is this rewrite of the kubectl configuration each time a user logs in expected or do we perhaps have something misconfigured?

```
# Begin logged in with a correct kubectl config
$ date ; $ kubectl get services
Thu Apr 18 13:01:02 CDT 2019
NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
kubernetes   ClusterIP   10.96.0.1    <none>        443/TCP   20h

# Wait for token to expire:
$ date ; kubectl get services
Thu Apr 18 13:06:21 CDT 2019
Unable to connect to the server: failed to refresh token: oauth2: cannot fetch token: 401 Unauthorized
Response: 

# Log in through Web UI and try kubectl again
$ date ; kubectl get services
Thu Apr 18 13:06:33 CDT 2019
Unable to connect to the server: failed to refresh token: oauth2: cannot fetch token: 401 Unauthorized
Response:

# Copy and paste kubectl configuration command from web UI
$ kubectl get services
NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
kubernetes   ClusterIP   10.96.0.1    <none>        443/TCP   20h

# Diff the old and new kubectl configurations. The refresh-token and id-token are different.
```

**Comment by mlbiam** [comment]
> Is this rewrite of the kubectl configuration each time a user logs in expected or do we perhaps have something misconfigured?

This is the correct behavior.  K8s isn't an OIDC client, it only knows how to pass a token and refresh it.  When your browser session ends (either via timeout or logout) OpenUnison deletes the user's stored session which stores the refresh token used to get a new id_token.  When kubectl tries to refresh its id_token the refresh_token is no longer valid.

You can observe this behavior by watching instances of `users` in the openunison namespace.  when a user logs in, a new one is created.  When a user logs out its deleted.  Also, should you want to instantly cut off a user's access, you would delete their `user` object breaking the ability to refresh their `id_token`.

**Comment by davideagen** [comment]
Ok thanks.
