### ISSUE TITLE
Add custom certificate to --auth-provider-arg=idp-certificate-authority-data

### ISSUE THREAD

**Issue by robertoayusob** [OpenUnison/openunison-k8s-login-activedirectory#48]
Hi

When we use our own certificates or ca on the ingress the commands shown on the unison portal to use kubectl keep showing the created by openunison application instead the ours, even if we put it on the extracerts configmap.

Due to this the kubectl command shows tls error.
```
Unable to connect to the server: Get https://.....auth/idp/k8sIdp/.well-known/openid-configuration: x509: certificate signed by unknown authority
```

The command should show on --auth-provider-arg=idp-certificate-authority-data= a value took from the configmap or add to the keystore on a specific entry the value took from the extracerts.

Thanks
Roberto

**Comment by mlbiam** [comment]
Are you using the latest version which uses an operator?  If so you'll need to:

1.  Delete the `ou-tls-certificate` secret
2.  in the `orchestra` `OpenUnison` object look for a key with the name `unison-ca` and delete it
3.  add the pem of your ca's cert as a `trusted_cert` with the name `unison-ca`

OpenUnison should redeploy refrencing the right cert in the command line

**Comment by robertoayusob** [comment]
Sorry I do not understand point 2. Which object is "orchestra Openunison" and how can I delete there that key? (I use kubernetes set up with kubeadm, not openshift)

**Comment by mlbiam** [comment]
sorry for the delay.  `OpenUnison` is the CRD thats used to drive the operator.  `orchestra` is the name of object.  so `kubectl get openunison orchestra -n openunison -o yaml` wiill get you the info.

**Comment by robertoayusob** [comment]
It does not exist.
```
$ kubectl get openunison orchestra -n openunison -o yaml                                                                                                            
error: the server doesn't have a resource type "openunison"
```
this is the get all
```
$ kubectl get all -n openunison
NAME                              READY   STATUS    RESTARTS   AGE
pod/openunison-798c98dd69-xvrwr   1/1     Running   2          2d22h


NAME                 TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE
service/openunison   ClusterIP   10.96.137.111   <none>        443/TCP,80/TCP   3d22h


NAME                         READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/openunison   1/1     1            1           3d22h

NAME                                    DESIRED   CURRENT   READY   AGE
replicaset.apps/openunison-798c98dd69   1         1         1       3d22h
```
We use kubernetes  1.14
```
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:45:25Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by mlbiam** [comment]
we've changed the deployment model, not sure why this didn't work but if you want to try with the new hem based deployer this answers how to handle custom certs - https://github.com/TremoloSecurity/OpenUnison/wiki/troubleshooting#how-do-i-change-openunisons-certificates
