### ISSUE TITLE
Getting StringIndexOutOfBoundsException when trying to deploy

### ISSUE THREAD

**Issue by TomerG711** [OpenUnison/openunison-k8s-login-activedirectory#49]
When I run the following command:

`curl https://raw.githubusercontent.com/TremoloSecurity/kubernetes-artifact-deployment/master/src/main/bash/deploy_openunison.sh | bash -s /path/to/orchestra-configmaps /path/to/orchestra-secrets https://raw.githubusercontent.com/OpenUnison/openunison-k8s-login-activedirectory/master/src/main/yaml/artifact-deployment.yaml`

(Using my path to the folders of course), the artifact-deployment pod gets an Error.
When I look into the pod logs using `kubectl log <pod_name> -n openunison-deploy` I can see the following error:
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -1
at java.lang.String.substring(String.java:1967)
at com.tremolosecurity.kubernetes.artifacts.run.RunDeployment.main(RunDeployment.java:91)

How could this happen?
Looking into the RunDeployment code which is under:
https://github.com/TremoloSecurity/kubernetes-artifact-deployment/blob/master/src/main/java/com/tremolosecurity/kubernetes/artifacts/run/RunDeployment.java

It seems that at line 91 it tries to read the deploymentTemplate, and yet it gets an error there.

**Comment by mlbiam** [comment]
Can you provide the full stacktrace?  the error is probably in the embedded javascript

**Comment by TomerG711** [comment]
@mlbiam  This is the full stacktrace I have.  When running `kubectl log` I can only see:
Processing - '/etc/extracerts/ldap.crt.pem'
Processing - '/etc/extracerts/..2019_10_03_22_09_15.934796652
'not a pem, sipping
Processing - '/etc/extracerts/..data'
not a pem, sipping
Processing - '/etc/extracerts/input.props'
not a pem, sipping
Processing - '/etc/extracerts/ldap.crt.pem'
Processing - '/etc/extracerts/..2019_10_03_22_09_15.934796652'
not a pem, sipping
Processing - '/etc/extracerts/..data'
not a pem, sipping
Processing - '/etc/extracerts/input.props'
not a pem, sipping
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -1        
at java.lang.String.substring(String.java:1967) 
at com.tremolosecurity.kubernetes.artifacts.run.RunDeployment.main(RunDeployment.java:91)

**Comment by mlbiam** [comment]
My guess is you have a blank line or line without a `=` in it.  script should be kore forgiving so I marked this as a bug.

**Comment by mlbiam** [comment]
since the bug is in https://github.com/TremoloSecurity/kubernetes-artifact-deployment/issues/1 will track updates to the code against that issue

**Comment by TomerG711** [comment]
@mlbiam The problem was indeed the fact that I had a line with a `=` in it.
