### ISSUE TITLE
Nginx Ingress Controller - "Service 'openunison/openunison-orchestra' does not have any active Endpoint."

### ISSUE THREAD

**Issue by TomerG711** [OpenUnison/openunison-k8s-login-activedirectory#52]
I've installed ingress-nginx for bare metal - https://kubernetes.github.io/ingress-nginx/deploy/. The installation was successful.
Then, I installed the OpenUnison portal, which was successful as well. When looking at the logs of the orchestra pod, there are now errors as well. 
However, when looking at the ingress controller pod logs I can see the following:
"Service 'openunison/openunison-orchestra' does not have any active Endpoint."
And the OpenUnison host is unreachable.
How can I fix this?

**Comment by mlbiam** [comment]
if the openunison host is unreachable, do you have it defined in DNS?  The openunison host name should point to the load balancer for your ingress controller

**Comment by TomerG711** [comment]
@mlbiam So I should additional load balancer, such as MetalLB, and configure the OU_HOST to the MetalLB?

**Comment by mlbiam** [comment]
if using a baremetal load balancer?  yes.  if you run `kubecetl get svc -n ingress-nginx` you'll see the port your ingress controller is running on.  It won't be 443.  You'll need something to redirecto to 443.  For testing I like to use an app called `pen`

**Comment by TomerG711** [comment]
@mlbiam  When I run `kubectl get svc -n ingress-nginx` I get the following:
NAME                 TYPE           CLUSTER-IP    EXTERNAL-IP    PORT(S)                                         AGE
ingress-nginx      NodePort        *.*.*.*          <none>            80:30699/TCP, 443:30626/TCP      7d2h

So 443 is indeed here...
I am running on baremetal, thus I will install MetalLB. After adding the LB, what services need to be added?
