### ISSUE TITLE
Helm Chart?

### ISSUE THREAD

**Issue by TJM** [OpenUnison/openunison-k8s-login-activedirectory#56]
Has anyone already created a helm chart for this? It seems like it would be useful.

Tommy

**Comment by mlbiam** [comment]
Not at the moment.  With Helm3's release we're looking into it.  We didn't want Helm to be a pre-requisite for installation when most of the work was really being done by an operator and found helm charts were lacking a level of flexibility around implementation.  I'll make this as a feature request as we're always looking to make the deployment easier.  We're happy to accept contributions here too.

**Comment by TJM** [comment]
@mlbiam Thanks for the speedy response! I certainly don't think helm should be required for installation either, but our organization is (standardizing?) on helmfile for deploying consistently to multiple environments. I will look into how hard it would be, it basically is a few go template yaml files, I think? For other applications, I have seen a "yaml" directory that you "modify" per the documentation, then `kubectl apply -f yamldir`, so I think helm (helmfile?) just automates the "modify" these yaml files to have a simple "values" file that provides the necessary customization steps (similar to your environment file).

**Comment by mlbiam** [comment]
Got it.  It should be pretty straight forward to be honest.  This is the line in the instructions to focus on:

`curl https://raw.githubusercontent.com/TremoloSecurity/kubernetes-artifact-deployment/master/src/main/bash/deploy_openunison.sh | bash -s /path/to/orchestra-configmaps /path/to/orchestra-secrets https://raw.githubusercontent.com/OpenUnison/openunison-k8s-login-activedirectory/master/src/main/yaml/artifact-deployment.yaml
`

The https://raw.githubusercontent.com/TremoloSecurity/kubernetes-artifact-deployment/master/src/main/bash/deploy_openunison.sh script does 4 things:

1.  Create the `openunison-deploy` namespace
2. Creates a `ConfigMap` with the non-secret configuration information and the certificates needed to trust AD
3.  Creates a `Secret` with the secret configuration data
4.  Creates a `Job` by running a create on https://raw.githubusercontent.com/OpenUnison/openunison-k8s-login-activedirectory/master/src/main/yaml/artifact-deployment.yaml

The `Job` in #4 then sets up RBAC rules, creates the `openunison` namespace and deploys the OpenUnison operator.  Once the operator is deployed and running it submits a CR that the operator picks up and runs with to deploy OpenUnison.

So a chart would include the `openunison-deploy` namespace, the artifact-deployment.yaml and the `Secret` and `ConfigMap` from the values.

**Comment by mlbiam** [comment]
We started working on some charts.  They require helm3 but are working pretty well - https://github.com/OpenUnison/helm-charts

**Comment by mlbiam** [comment]
helm is now the standard way to deploy
