### ISSUE TITLE
openunison-orchestra Terminating

### ISSUE THREAD

**Issue by mikarnik** [OpenUnison/openunison-k8s-login-activedirectory#63]
I have fresh instalation of k8s cluster 1.18 - 1 master 1 node (calico). Siple metalLB, ingress-nginx, kubernetes-dashboard. When I try install openunison using Helm with verified values.yaml etc. Operator creates all resources like svc, but openunison-orchestra is still ContainerCreating and Terminating. Pods are Terminated arfter few seconds.

openunison             openunison-operator-7d58975678-wt6lm             1/1     Running             0          11m
openunison             openunison-orchestra-66b547d6b6-m5lwf            0/1     Terminating         0          7s
openunison             openunison-orchestra-7d688cd5bb-wkhz7            0/1     ContainerCreating   0          1s
openunison             openunison-orchestra-8556b6c956-hc9gv            0/1     Running             0          4s
openunison             openunison-orchestra-85b59f5bcd-sv766            0/1     Terminating         0          9s
openunison             openunison-orchestra-94f745f66-vssnb             0/1     Terminating         0          10s

There isn't any error in the openunison-orchestra log.

**Comment by mlbiam** [comment]
odd.  a few questions:

1.  How did you deploy k8s?  kubeadm?
2.  Take a look at the operator logs, do they look like they'r constantly deploying?
3.  what does kubectl get events -n openunison say?

**Comment by mikarnik** [comment]
1. kubeadm


2. operator logs again and again
Resource Version - 39625 - false
in js : {"type":"MODIFIED","object": ....
....
Processing key 'unison-tls'


3. Erros from events

14m         Warning   Failed                         pod/openunison-orchestra-ffc67b749-c4m9n     Error: cannot find volume "secret-volume" to mount into container "openunison-orchestra"

25m         Warning   FailedToUpdateEndpoint         endpoints/openunison-orchestra               Failed to update endpoint openunison/openunison-orchestra: Operation cannot be fulfilled on endpoints "openunison-orchestra": the object has been modified; please apply your changes to the latest version and try again
23m         Warning   FailedToUpdateEndpointSlices   service/openunison-orchestra                 Error updating Endpoint Slices for Service openunison/openunison-orchestra: Error updating openunison-orchestra-ckdl5 EndpointSlice for Service openunison/openunison-orchestra: Operation cannot be fulfilled on endpointslices.discovery.k8s.io "openunison-orchestra-ckdl5": the object has been modified; please apply your changes to the latest version and try again

**Comment by mlbiam** [comment]
Odd.  the resource version is the same on each repeat?  Just upgraded my test cluster to 1.18.  Lets see if I can reproduce

**Comment by mikarnik** [comment]
Resource Version is changing.

**Comment by mlbiam** [comment]
huh.  can you capture the json from subsequent `MODIFIED` statements and see whats changing?  The operator only acts if there are changes to `metadata.annotations`,`metadata.labels`, and `spec`.  Any other changes should be ignored

**Comment by mikarnik** [comment]
in js : {"type":"MODIFIED","object": .... changing only
"operation":"Update","time":"2020-03-28T14:39:17Z"
"resourceVersion":"53408"
"lastTransitionTime":"2020-03-28 02:39:17GMT"
"digest":"K88OD7gAemRgAWs/5We/eKqiQ5YkjyQo+ljPCt/awGg="

**Comment by mikarnik** [comment]
Resource Version - 53172 - false
Resource Version - 53212 - false
Resource Version - 53307 - false
Resource Version - 53360 - false
...

**Comment by mlbiam** [comment]
You deployed this new cluster with the helm charts?

**Comment by mikarnik** [comment]
Yes with helm charts.

**Comment by mlbiam** [comment]
ok, good news.  a fresh k8s cluster and i can reproduce the issue.  must be something introduced with 1.18.  Thanks for the catch, let me get a fix in.

**Comment by mlbiam** [comment]
ok, i think its fixed:

1.  Delete your orchestra helm deployment - `helm delete orchestra --namespace openunison`
2.  Delete your operator pod - `kubectl delete pods -l app=openunison-operator -n openunison`
3.  Once the operator pod is running again, redeploy your orchestra helm deployment `helm install orchestra . --namespace openunison -f /tmp/k8s-idm-lab/values.yaml`

**Comment by mikarnik** [comment]
great, I can confirm it works! thank you
