### ISSUE TITLE
Own TLS Certificate ans SSO

### ISSUE THREAD

**Issue by mikarnik** [OpenUnison/openunison-k8s-login-activedirectory#64]
I have replaced a self-signed certificate for OpenUnison and the Kubernetes Dashboard:
kubectl -n openunison edit secrets ou-tls-certificate

This works. I see trusted certificates at OpenUnison portal.

Now I want to set up SSO Integration with Kubernetes. I copy my certificate chain to /etc/kubernetes/pki/ou-ca.pem and setup --oidc-ca-file etc.

Opening dashboard end with an error.
INFO  AccessLog - [Error] - k8s - https://dashboard.company.local/auth/oidc - uid=...
ERROR ConfigSys - Could not process request
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

I'm not sure what format ou-ca.pem is expected in the case of the certificate chain.

btw - SSO Integration works with original self-signed certificate

**Comment by mlbiam** [comment]
Which secret did you replace?

**Comment by mlbiam** [comment]
Nm saw it in your comment. When you replaced the certificate did you also replace the private key?  Did you update the `orchestra` cr to force a redeploy?

**Comment by mikarnik** [comment]
yes both tls.crt and tls.key in ou-tls-certificate

What do you mean update the orchestra cr?

**Comment by mikarnik** [comment]
In web portal, the - OpenUnison Server CA Certificate is the certificate of OpenUnison an Dashboard not the CA.

**Comment by mlbiam** [comment]
Here are the steps you need to take (I realize i missed some details in my instructions on the readme):

1.  Generated a new self signed key pair
2.  Replaced `tls.crt` and `tls.key` in `ou-tls-certificate`
3.  Make some kind of update to the `orchestra` `openunison` object to trigger a redeploy - I usually add a `metadata.annotation` (kubectl edit openunison orchestra -n openunison)
4.  Make some kind of update to the `openunison` ingress object, sometimes the Ingress controller doesn't pick up new certificate

**Comment by mikarnik** [comment]
I updated the orchestra the openunison object (add annotation), but nothing happend.
operator log :
Loading Script : '/usr/local/openunison/js/deploy-objs.js'
Loading Script : '/usr/local/openunison/js/deploy-openshift.js'
Loading Script : '/usr/local/openunison/js/deploy-upstream-k8s.js'
Loading Script : '/usr/local/openunison/js/globals.js'
Loading Script : '/usr/local/openunison/js/helpers.js'
Loading Script : '/usr/local/openunison/js/operator.js'
/apis/openunison.tremolo.io/v1/namespaces/openunison/openunisons?watch=true&resourceVersion=230939
Is OpenShift : false
Resource Version - null - true
Resource - null - already processed, skipping

One more thing helm -n openunison uninstall orchestra didn't work. All resources were still in namespace.

**Comment by mlbiam** [comment]
> I updated the orchestra the openunison object (add annotation), but nothing happend.
operator log :
Loading Script : '/usr/local/openunison/js/deploy-objs.js'
Loading Script : '/usr/local/openunison/js/deploy-openshift.js'
Loading Script : '/usr/local/openunison/js/deploy-upstream-k8s.js'
Loading Script : '/usr/local/openunison/js/globals.js'
Loading Script : '/usr/local/openunison/js/helpers.js'
Loading Script : '/usr/local/openunison/js/operator.js'
/apis/openunison.tremolo.io/v1/namespaces/openunison/openunisons?watch=true&resourceVersion=230939
Is OpenShift : false
Resource Version - null - true
Resource - null - already processed, skipping

Hmm, thats odd.  that means the resource version wasn't included in the request.  Not sure how thats even possible.  How are you editing the `orchestra` object?  kubectl edit?

> One more thing helm -n openunison uninstall orchestra didn't work. All resources were still in namespace.

I'm using `helm delete orchestra   --namespace openunison` and works fine.  Can you try that?

**Comment by mikarnik** [comment]
1. I had to delete openunison-operator to start a new pod and this helped. On the second cluster, I did the same then I did some changes and I had to delete openunison-operator again. But finally, it works. 
2. helm delete works

Now I have a first cluster running with "public" certificate and all works. Login, Dashboard, and kubectl config. I had to include intermediate CA cert to public certificate. Now I will try to setup second cluster with internal CA certificates.

Thanks a lot for your help.
Michal

**Comment by mikarnik** [comment]
one more question the client kubectl cant refresh the token:
failed to refresh token: oauth2: cannot fetch token: 401 Unauthorized

**Comment by mlbiam** [comment]
1.  I put together what I think are better instructions on how to replace the certs - https://github.com/TremoloSecurity/OpenUnison/wiki/troubleshooting#how-do-i-change-openunisons-certificates. 
2.  I managed to reproduced the issue with "null" resource version, but I'm not really sure how.  I'll keep trying to reproduce to see if I can figure that one out

> failed to refresh token: oauth2: cannot fetch token: 401 Unauthorized

Usually means your refresh token expired.  Go ahead and refresh the screen that you got the token from and you should have a new set of tokens

**Comment by mikarnik** [comment]
Thank for the wiki.

Can I set longer validity of the token? It expires in 5 minutes I think.

**Comment by mlbiam** [comment]
try setting your image in the cr to `docker.io/tremolosecurity/betas:k8s-login-ad-1.0.18`.  we fixed a bug in how we handle timeouts.

> https://www.tremolosecurity.com/wiki/#!kubernetes.md
As understand I have to refresh ScaleJS Token screen to keep it alive. Alternatively run kubectl command kubectl --token=`curl ... Or is there another way?

wow, i wrote that 4 years ago before I rewrote the k8s oidc docs :-). I'd ignore it.

**Comment by mikarnik** [comment]
Works great :+1:

**Comment by mikarnik** [comment]
What is the timeout now? I closed web browser and kubectl is still working.

**Comment by mlbiam** [comment]
The default idle timeout is still 15 minutes. The difference is token refreshes count against that. So each token is only good for a minute or so but if you keep working with kubectl every refresh buys you another 15 minutes without logging in. If you explicitly logout or go fifteen minutes without refreshing the token your cli session will end

**Comment by mikarnik** [comment]
It's really good.  Can I set the default 15 min timeout to something else or not?

**Comment by mlbiam** [comment]
Yes. In the cr change `SESSION_INACTIVITY_TIMEOUT_SECONDS` to the number of seconds you want the idol timeout to be. Right now it's 900 (15 min)

**Comment by mikarnik** [comment]
FYI When I change something in cr, new pod is created, but the dashboard stop working.  I have to change something in the ingress as you told me and delete the pod to recreate it. After this Dashboard works again.

**Comment by mlbiam** [comment]
The dashboard stops working even after you get to ready 1/1?

**Comment by mikarnik** [comment]
I did a fresh install to review my install guide and all works fine. :)

I have another question about RBAC.
I want to setup the view role to "developers" group. I's ok and it works - clusterrolebinding role view to CN=developers,.... 

Then I create namespace "johndoe" and I wan to set user johndoe admin role to this namespace. Usually (AWS) I setup rolebinding of clusterrole admin in this namespace.  User johndoe is member of  developers group and also his own johndoe-group. To use Group Driven Membership I use this personal group for rolebindiing - rolebinding role admin to CN=johndoe-group,... I can list the namespace, but can't create any object:
Error from server (Forbidden): error when creating ... cannot create resource "configmaps" in API group "" in the namespace "johndoe"

Is there anythin different in openunison?

**Comment by mikarnik** [comment]
Using User Driven Membership works:
kubectl create rolebinding johndoe-binding --clusterrole=admin --user=https://k8sou.tremolo.lan/auth/idp/k8sIdp#123e4567-e89b-12d3-a456-426655440000 --namespace=johndoe

I don't understand why Group Driven Membership doesn't. It works with clusterrolebinding.

**Comment by mlbiam** [comment]
Should work OK.  Whats your RBAC rule look like?  You can check to make sure your group memberships are what your are expecting in 3 ways:

1. You can take the `id_token` and put it into https://jwt.io and it will inspect the token (jwt.io doesn't send the token anywhere, its all client side)
2. In the openunison portal, click on your user id in the upper left hand corner and you'll see what groups you're a member of
3.  Look in your namespace for user objcts (`k get users -n openunison -o yaml`)

**Comment by mikarnik** [comment]
It works. Sorry, probably I had some misspells in yaml. Thank you for all the answers. Now everything works as I expected.

**Comment by mlbiam** [comment]
awesome.  i'll close this out
