### ISSUE TITLE
Customizing the look and feel 

### ISSUE THREAD

**Issue by vbottu** [OpenUnison/openunison-k8s-login-activedirectory#72]
I am looking to customize the look and feel of the login portal, all jsp's are part of that war file that is packaged. Is there a way to customize the look and feel like changing the logo's ? Thanks

**Comment by mlbiam** [comment]
yes.  Whatever you put in your repo will override whats in the original war.  For instance to use your company's own image, place it in `src/main/webapp/auth/forms/img/ts_logo.png` and that will load instead of the tremolo security logo.

**Comment by vbottu** [comment]
Thanks.
