### ISSUE TITLE
old expired sessions

### ISSUE THREAD

**Issue by brackend** [OpenUnison/openunison-k8s-login-activedirectory#91]
Old expired sessions are used by open unison.   
Using oulogin, the session times out is set to 2 hours.  So refresh occurs transparently.  After 2 hours the user is redirected to the login portal and a new session is created set to expire in another 2 hours.
But after another 2 mins, on the refresh, the user is redirected to the login page again.  It continues to behave like this
, ie redirected every 2 minutes.  At the same time ou is generating a new session resource in k8s for each redirected action.  What seems to be happening is the refresh token finds the old expired session instead of finding the new session.  And so tries to creat a new session each time.  The effect is multiple session resources are created from multiple redirects/refreshes.  So when I delete the old expired session resource, the problem is solved.  That is,  the token refresh finds the newer session instead of the now deleted older session.  Is this a bug?  How long do expired sessions live for?  Why are old sessions active? Should I just increase the timeout - not really appropriate for security.

**Comment by mlbiam** [comment]
@brackend I found why old session objects aren't being deleted.  There was a misconfiguration on the `Job` that kept the cleanup process from running.  Pull the latest container and your sessions should be cleaned up without issue.

looking at the issue you're seeing with the `oulogin` plugin creating too many sessions now

**Comment by brackend** [comment]
Super! Nice work!  I thought setting the session inactivity timeout too
high might have been responsible.  I’ll check that change.

**Comment by mlbiam** [comment]
> If I understand the question, each cluster hosts its own openunison
deployment.  

yes

>  Primarily values files differentiate the deployments for each
cluster.
Right, specifically `k8s_cluster_name`.  Is this different for each cluster?  What you're describing sounds like when a cluster configuration overlaps another cluster's configuration in the kubectl config file.  OpenUnison sets the kubectl `userName` to `user@k8s_cluster_name` so if multiple clusters share the same name it will force you to log back in.

**Comment by brackend** [comment]
Yes k8s_cluster_names uniquely identify each cluster. Along with ingress
urls etc.

My thought was that more sessions were created because OU always found the
expired session and not the new active one(s)…thinking there was no active
session. If that is the case then I now shouldn’t see multiple sessions.

**Comment by brackend** [comment]
Using the latest: https://hub.docker.com/r/tremolosecurity/openunison-k8s-login-activedirectory/tags ( 17 hours ago)
Still got the same issue.   Also seeing multiple sessions created with following expiries.  
2021-10-10T21:30:24.582Z

2021-10-10T21:25:47.884Z

2021-10-11T06:45:49.130Z

2021-10-10T21:19:46.590Z

2021-10-10T21:17:20.300Z

2021-10-10T21:24:38.602Z

2021-10-10T21:31:42.216Z

2021-10-10T21:27:08.177Z

2021-10-11T07:09:37.900Z

2021-10-10T21:28:49.316Z

2021-10-10T21:30:47.441Z

**Comment by mlbiam** [comment]
Can you double check that there are no other contexts in the kubectl config file? There's an issue with creating two sessions on login with the oulogin plugin i'm looking at now.  but otherwise i'm not able to reproduce what you're seeing.

**Comment by brackend** [comment]
It looks like the first issue is fixed with the latest container configuration.   There are no more expired sessions. 

As for continuing session stability problems...  It turned out that it was an outdated kubectl client.   You pointed me to kube config which lead me to the client I was using.  There were two versions running on my machine. One outdated.  

I'm still seeing multiple sessions but so far they don't appear to be affecting our access experience. 

Thank you for help.
